services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db:3306/pet_app?serverVersion=8.0

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:20-alpine
    container_name: symfony_node
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
